Added optional params subject_text and body_text…
mdomke/concourse-email-resource pull request #1
Opened 2016-10-03 12:11 UTC by knifhen

…  that can be used instead of reading subject and body from files

2016-10-03 16:57 UTC, mdomke requested changes
Hi @knifhen! Thanks for your pull-request! I appreciate your contribution very much! Nevertheless I think that some things should be handled a little different from the way you implemented it. It would be great if you could adjust your pull-request accordingly or give some feedback on why you think it should be as it is.

2016-10-03 16:57 UTC, mdomke commented on README.md
> +* `subject_text`: _(optional)_ Plain text email subject, instead of `subject`.
Could you make clear that either the `subject_text` *or* the `subject` option have to be supplied. The same applies for the `body` and the `body_text`.

2016-10-03 16:57 UTC, mdomke commented on opt/resource/out
> +            return Template(fp.read()).render(template_vars)
I would rather use a variable `subject` for both config values `'subject_text'` and `'subject'` and assign its value accordingly. Additionally I think that the template variables should be applied in any case.

```python
    subject = get_value_from_payload(payload, 'params', 'subject_text', optional=True)
    if not subject:
        fname = get_value_from_payload(payload, 'params', 'subject')
        with open(os.path.join(src, fname)) as fp:
            subject = fp.read()
    return Template(subject).render(template_vars)
```

2016-10-03 16:57 UTC, mdomke commented on opt/resource/out
> +    if not body_text:
As described above. The body should be read either from the constant text in `'body_text'` or from the file `'body'`. All other operations (e.g: css inlining, template variable application) should be applied regardless of the source of the body-text.

```python
body = get_value_from_payload(payload, 'params', 'body_text', optional=True)
if not body:
    fname = get_value_from_payload(payload, 'params', 'body')
    with open(os.path.join(src, fname)) as fp:
        message = fp.read()
message = Template(message).render(template_vars)
...
if mime_subtype == 'html' and inline:
    ...
return message
```

2016-10-03 18:24 UTC, knifhen commented
Hi @mdomke, I tried to make the pull request more to your specification. Hope this works better!

Regards Andreas Knifh

2016-10-04 08:58 UTC, mdomke approved these changes

2016-10-04 08:59 UTC, merged