Added to_file option
mdomke/concourse-email-resource pull request #4
Opened 2016-10-12 19:25 UTC by hryamzik

Added an option to specify recipients with a file, very useful if you want to send an email to the commit author.

2016-10-13 10:49 UTC, mdomke requested changes
Hey @hryamzik many thanks for your pull-request! The ability to dynamically specify the list of recipients seems to be something people might find useful ;-)

2016-10-13 10:49 UTC, mdomke commented on opt/resource/out
> +        if not isinstance(recipients, list):
I would prefer to have only one type-check for the reciepients list. E.g.:
```python
recipients = get_value_from_payload(payload, 'params', 'to', optional=True)
if not recipients:
    ...
if not isinstance(recipients, list):
    raise ValueError("The recipients parameter has to be a list!")
```

2016-10-13 11:07 UTC, hryamzik commented
@mdomke please see the changes.

2016-10-25 23:14 UTC, mdomke requested changes

2016-10-25 23:14 UTC, mdomke commented on README.md
> +* `to|to_file`: _(mandatory)_ Use `to` to specify a list of recipients as strings or use `to_file` to cpecify file with addresses, each address should be in a new line.
Hi @hryamzik thank you for your pull-request and sorry for the late reply. Would you mind to fix the typo "cpecify" -> "specify" and I'll gladly merge it!

2016-10-31 09:13 UTC, hryamzik commented on README.md
> +* `to|to_file`: _(mandatory)_ Use `to` to specify a list of recipients as strings or use `to_file` to cpecify file with addresses, each address should be in a new line.
Indeed, done.

2017-03-20 15:57 UTC, mrmcmuffinz commented
Hi, is there an eta when this will go in?

2017-03-20 17:42 UTC, hryamzik commented
@mrmcmuffinz feel free to use this image:

```yml
  - name: email-forked
    type: docker-image
    source:
      repository: incaller/concourse-email-resource
```

2017-03-20 17:46 UTC, mdomke commented
Sorry, I lost track of this PR. I'll merge it tonight and provide an updated docker image. I'm sorry for the inconvenience.

2017-03-21 06:45 UTC, mdomke approved these changes

2017-03-21 06:46 UTC, merged

2017-03-21 06:53 UTC, mdomke commented
The updated image is now available on [dockerhub](https://hub.docker.com/r/mdomke/concourse-email-resource/).

2017-03-21 14:53 UTC, mrmcmuffinz commented
@mdomke it's not a problem, I was just wondering when the feature was going to come in. Either way thanks to both of you( @hryamzik & @mdomke  )for providing the resource.